012 add modal info
tkachor/dot-net-club3 pull request #13
Opened 2022-02-11 18:14 UTC by Sanchose

2022-02-11 19:21 UTC, Giorgio-77 approved these changes

2022-02-11 20:23 UTC, MaksymHertsun requested changes
Please, delete footer section from here. This was done in the previous issue, and will cause conflict.

2022-02-11 20:59 UTC, TetKopot approved these changes

2022-02-12 09:48 UTC, MaksymHertsun approved these changes

2022-02-12 09:48 UTC, merged